### ISSUE TITLE
have some problems

### ISSUE THREAD

**Issue by 687766616e** [HatBashBR/HatDecrypter#1]
$ python hatdecrypter.py -t 0 -p ebea25dadcb23a11ff3fd991f94f3665
  File "hatdecrypter.py", line 36
    print "Voce precisa definir um tipo de hash!"
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Voce precisa definir um tipo de hash!")?
$ python2 hatdecrypter.py -t 0 -p ebea25dadcb23a11ff3fd991f94f3665
Traceback (most recent call last):
  File "hatdecrypter.py", line 3, in <module>
    import crackers, threading, time, itertools
  File "/data/data/com.termux/files/home/Hat/crackers.py", line 4, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by mateeuslinno** [comment]
You need install bs4
pip install beautifulsoup4

**Comment by 687766616e** [comment]
@mateeuslinno $ pip install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in /data/data/com.termux/files/usr/lib/python3.6/site-packages
$

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by mateeuslinno** [comment]
Do you install ? run python 
https://i.imgur.com/xMtv3Vy.png

**Comment by evertonch** [comment]
you need to install the libraries, here is how:
pip install bs4 passlib
pip2 install bs4 passlib
i think the problem is that your default python is 3.5 so pip will only install the libraries for python 3.5, and that's why it shows an error in the first example, this program is made to run on python2.
so running pip2 install bs4 passlib and then running the program with python2 should work!
